### ISSUE TITLE
S1 tftpboot syntax

### ISSUE THREAD

**Issue by frakman1** [AntMiner/AntGen1#10]
I bricked the **S1 AntMiner** openWRT/controller and  need to recover. I am able to get a serial prompt and pressed 'p' to stop autoboot. I am connected to laptop with 192.168.1.100 address and TFTP server for image: `antMiner_openwrt20131212.bin`

Now I need the exact tftpboot syntax for the S1. I found the S3 syntax on an [online forum:
](https://bitcointalk.org/index.php?topic=775662.0)
```
tftpboot 0x80000000 antMiner_S320150109.bin
erase 0x9f020000 +0x7c0000
cp.b 0x80000000 0x9f020000 0x7c0000
reset 

```
What is the exact syntax to use with the **S1**?

**Comment by jameshilliard** [comment]
It should be the same, just replace `antMiner_S320150109.bin` with `antMiner_openwrt20131212.bin` in the tftpboot command.

**Comment by frakman1** [comment]
Thank you James. I was afraid the memory locations were different and would cause an irrecoverable memory clobber. I found another command to do it via http and from examining the logs, it appears to use the same address offsets as the S3.

It's back up now.
